# Generated by Django 5.1.1 on 2024-09-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='societe',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('facture', 'FACTURE'), ('devis', 'DEVIS'), ('Proforma', 'Proforma')], default='facture', max_length=200),
        ),
    ]
